### ISSUE TITLE
Can't implement dark mode & border radius

### ISSUE THREAD

**Issue by deadcoder0904** [gradints/tailwindcss-scrollbar#4]
I want my scrollbar to look like this:

<img width="30" alt="Screenshot 2022-03-27 at 2 38 46 PM" src="https://user-images.githubusercontent.com/16436270/160274703-0ab75dea-a5a4-4670-869c-60c57224f4fd.png">

the code for the above is:

```css
::-webkit-scrollbar {
	/* h-[10px] => height of horizontal scrollbar, w-[10px] => width of vertical scrollbar */
	@apply h-[10px] w-[10px] bg-gray-200 dark:bg-scrollbar;
}

::-webkit-scrollbar-track {
	@apply rounded-md bg-transparent;
}

::-webkit-scrollbar-thumb {
	@apply rounded-md bg-gray-500 dark:bg-gray-300;

	&:hover {
		@apply bg-gray-400 dark:bg-gray-400;
	}
}
```

but instead when i used this plugin, it looks like:

<img width="30" alt="Screenshot 2022-03-27 at 2 40 19 PM" src="https://user-images.githubusercontent.com/16436270/160274755-cd30d85a-1537-456c-8cfb-9e2c7d38f41b.png">

notice, the thumb is square & there is no background color.

the code looks like:

```css
scrollbar: (theme) => ({
			DEFAULT: {
				size: theme('spacing.3'),
				borderRadius: theme('borderRadius.md'),
				colors: {
					track: theme('colors.transparent'),
					thumb: theme('colors.gray.500'),
					thumbHover: theme('colors.gray.400'),
				},
				backgroundColor: theme('bg-gray-200'),
			},
			dark: {
				size: theme('spacing.3'),
				borderRadius: theme('borderRadius.md'),
				colors: {
					track: theme('colors.transparent'),
					thumb: theme('colors.gray.300'),
					thumbHover: theme('colors.gray.400'),
				},
				backgroundColor: theme('bg-scrollbar'),
			},
		}),
```

what am i doing wrong?

i have just commented my `scrollbar.css` file so my `bg-scrollbar` variable is still present but it isn't giving me the same output.

would love to use this plugin :)

**Comment by christhofer** [comment]
Didn't know we can use border radius there.
Currently this plugin doesn't support attribute borderRadius, I'll add it later today after I'm back from work.

**Comment by deadcoder0904** [comment]
thanks. also, the background color isn't working if u can compare both the screenshots.

fwiw, i want the 2nd one to look exactly like the 1st one :)

**Comment by christhofer** [comment]
@deadcoder0904 

What is your `theme('bg-scrollbar')` does?

For background color, change the property inside colors

```
scrollbar: theme => ({
      DEFAULT: {
        size: theme('spacing.1'),
        colors: { 
          track: theme('colors.gray.300'), 
          thumb: theme('colors.gray.100'), // change this value to your color, this will apply css property background, which I believe what you are asking
          thumbHover: theme('colors.gray.600'), // this is when the scroll bar is hovered
        }
      },
    })
```

**Comment by deadcoder0904** [comment]
@christhofer 

no, that's different. my `bg-scrollbar` is inside `theme > extend > colors` that looks like:

```css
theme: {
	extend: {
		colors: {
			'primary-lighter': 'hsl(0, 0.0%, 15.0%)',
			'primary-light': 'hsl(0, 0.0%, 12.0%)',
			primary: 'hsl(0, 0.0%, 9.0%)',
			'primary-dark': 'hsl(0, 0.0%, 6.0%)',
			'primary-darker': 'hsl(0, 0.0%, 3.0%)',
			scrollbar: 'hsla(0, 0%, 100%, 0.1)',
			syntaxBg: 'hsl(0, 0.0%, 12%)',
		},
	}
}
```

you are little wrong about that 2nd part. i thought i must use `backgroundColor` property but what i wanted was to use `track` property like this:

```js
scrollbar: (theme) => ({
	DEFAULT: {
		size: theme('spacing.3'),
		borderRadius: theme('borderRadius.md'),
		colors: {
			track: theme('colors.gray.200'),
			thumb: theme('colors.gray.500'),
			thumbHover: theme('colors.gray.400'),
		},
	},
	dark: {
		size: theme('spacing.3'),
		borderRadius: theme('borderRadius.md'),
		colors: {
			track: theme('colors.scrollbar'),
			thumb: theme('colors.gray.300'),
			thumbHover: theme('colors.gray.400'),
		},
	},
}),
```

this worked.

`borderRadius` doesn't work & i think dark theme isn't working either.

this is how it should look (this is my `scrollbar.css` file):

<img width="193" alt="Screenshot 2022-03-28 at 12 59 11 PM" src="https://user-images.githubusercontent.com/16436270/160347892-a2ae5d28-59a3-44c8-a58a-478a00dbd299.png">

this is how it looks:

<img width="193" alt="Screenshot 2022-03-28 at 1 00 00 PM" src="https://user-images.githubusercontent.com/16436270/160348014-fd2893b5-6961-4563-a4d6-0b9dbd42c93f.png">

i've kept `tailwind.config.js` (see the above code) exactly like my `scrollbar.css` file (see my 1st comment for code)
